services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "${APP_WEB_PORT}:80"
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      args:
        gid: ${GID}
        uid: ${UID}
        xdebug_idekey: ${XDEBUG_IDEKEY}
        xdebug_client_port: ${XDEBUG_CLIENT_PORT}
        target: dev
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - ./:/var/www/app
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./docker/config/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "${APP_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:8.2.0-alpine
    volumes:
      - redis-data:/data
    ports:
      - "${APP_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  npm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/node/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-npm
    volumes:
      - ./:${APP_PATH}:cached
      - ./.env:${APP_PATH}/.env
    working_dir: ${APP_PATH}
    profiles: ["npm"]
    entrypoint: ['npm']
    ports:
      - "${APP_VITE_PORT}:5173"

  scheduler:
    container_name: ${COMPOSE_PROJECT_NAME}-scheduler
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: scheduler
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm-dev.d/www.conf
    restart: on-failure
    depends_on:
      - php

  worker:
    container_name: ${COMPOSE_PROJECT_NAME}-worker
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: worker
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/php/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm-dev.d/www.conf
    restart: on-failure
    depends_on:
      - php

volumes:
  db-data:
  redis-data: